-- AlterTable
ALTER TABLE "user_profiles"
ADD COLUMN IF NOT EXISTS "target_role" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "experience_level" VARCHAR(50),
ADD COLUMN IF NOT EXISTS "target_companies" JSONB,
ADD COLUMN IF NOT EXISTS "country" VARCHAR(10),
ADD COLUMN IF NOT EXISTS "region" VARCHAR(255),
ADD COLUMN IF NOT EXISTS "salary_min" INTEGER,
ADD COLUMN IF NOT EXISTS "salary_max" INTEGER,
ADD COLUMN IF NOT EXISTS "work_arrangements" JSONB,
ADD COLUMN IF NOT EXISTS "preferred_job_types" JSONB;
