export { COUNTRY_OPTIONS } from '@/constants/options';

export const LOCATION_OPTIONS: Record<string, Array<{ label: string; value: string }>> = {
  gb: [
    { label: 'London', value: 'London' },
    { label: 'South East England', value: 'South East England' },
    { label: 'North West England', value: 'North West England' },
    { label: 'West Midlands', value: 'West Midlands' },
    { label: 'Scotland', value: 'Scotland' },
    { label: 'East of England', value: 'East of England' },
    { label: 'South West England', value: 'South West England' },
    { label: 'East Midlands', value: 'East Midlands' },
    { label: 'North East England', value: 'North East England' },
    { label: 'Yorkshire', value: 'Yorkshire and The Humber' },
    { label: 'Wales', value: 'Wales' },
    { label: 'Northern Ireland', value: 'Northern Ireland' },
  ],
  us: [
    { label: 'New York', value: 'New York' },
    { label: 'California', value: 'California' },
    { label: 'Texas', value: 'Texas' },
    { label: 'Washington', value: 'Washington State' },
    { label: 'Massachusetts', value: 'Massachusetts' },
    { label: 'Illinois', value: 'Illinois' },
    { label: 'Pennsylvania', value: 'Pennsylvania' },
    { label: 'Colorado', value: 'Colorado' },
    { label: 'Georgia', value: 'Georgia' },
    { label: 'Florida', value: 'Florida' },
  ],
  de: [
    { label: 'Berlin', value: 'Berlin' },
    { label: 'Bayern', value: 'Bayern' },
    { label: 'Hamburg', value: 'Hamburg' },
    { label: 'Hessen', value: 'Hessen' },
    { label: 'NRW', value: 'Nordrhein-Westfalen' },
    { label: 'Baden-Württemberg', value: 'Baden-Württemberg' },
    { label: 'Sachsen', value: 'Sachsen' },
  ],
  fr: [
    { label: 'Île-de-France', value: 'Île-de-France' },
    { label: 'Auvergne-Rhône-Alpes', value: 'Auvergne-Rhône-Alpes' },
    { label: 'Provence-Alpes-Côte d\'Azur', value: 'Provence-Alpes-Côte d\'Azur' },
  ],
  nl: [
    { label: 'Noord-Holland', value: 'Noord-Holland' },
    { label: 'Zuid-Holland', value: 'Zuid-Holland' },
    { label: 'Noord-Brabant', value: 'Noord-Brabant' },
  ],
  au: [
    { label: 'New South Wales', value: 'New South Wales' },
    { label: 'Victoria', value: 'Victoria' },
    { label: 'Queensland', value: 'Queensland' },
    { label: 'Western Australia', value: 'Western Australia' },
  ],
  ca: [
    { label: 'Ontario', value: 'Ontario' },
    { label: 'British Columbia', value: 'British Columbia' },
    { label: 'Alberta', value: 'Alberta' },
    { label: 'Quebec', value: 'Québec' },
  ],
  in: [],
  sg: [],
  at: [],
  be: [],
  br: [],
  it: [],
  pl: [],
  za: [],
};

export const JOB_TITLE_OPTIONS = [
  'Software Engineer',
  'Senior Software Engineer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'DevOps Engineer',
  'Data Scientist',
  'Data Engineer',
  'Data Analyst',
  'Machine Learning Engineer',
  'Cloud Engineer',
  'Mobile Developer',
  'iOS Developer',
  'Android Developer',
  'QA Engineer',
  'Security Engineer',
  'Solutions Architect',
  'Technical Lead',
  'Engineering Manager',
  'Product Manager',
  'Project Manager',
  'UX Designer',
  'UI Developer',
  'Business Analyst',
  'Database Administrator',
  'System Administrator',
  'Network Engineer',
  'Cyber Security Analyst',
  'Scrum Master',
  'IT Consultant',
];
