services:
  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    depends_on: [backend]

  backend:
    build: ./apps/backend
    ports:
      - "4000:4000"
    depends_on: [postgres, mongo]

  ml-service:
    build: ./apps/ml-service
    ports:
      - "5000:5000"
    depends_on: [postgres, mongo]

  postgres:
    image: postgres:17
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  mongo:
    image: mongo:7
    ports: ["27017:27017"]

volumes:
  postgres_data:
  mongo_data:
